name: calacirya
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/fatiharge/calacirya.git

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  mazarbul: ^1.0.9
  lottie: ^2.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/